CREATE DATABASE IF NOT EXISTS anotes;

CREATE USER IF NOT EXISTS 'zenusr'@'%' IDENTIFIED BY 'strongPass!2024';

GRANT ALL PRIVILEGES ON *.* TO 'zenusr'@'%' WITH GRANT OPTION;
GRANT SELECT ON anotes.* TO 'zenusr'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;